'use client'

/**
 * OSMOS Research Axes Section v2 - Dark Elegance Edition
 *
 * Displays structured research axes generated by the ResearchAxesEngine v2.
 * Each axis has a role (actionnable, risk, structure) and shows
 * the KG relationship that generated it.
 */

import {
  Box,
  HStack,
  VStack,
  Text,
  Tooltip,
  Icon,
  Collapse,
  useDisclosure,
  Badge,
} from '@chakra-ui/react'
import {
  ChevronDownIcon,
  ChevronUpIcon,
} from '@chakra-ui/icons'
import { ResearchAxis } from '@/types/api'
import { FiCompass, FiZap, FiAlertTriangle, FiLayers } from 'react-icons/fi'

// Configuration par role
const ROLE_CONFIG: Record<string, { icon: any; color: string; bg: string; label: string }> = {
  actionnable: {
    icon: FiZap,
    color: 'green.400',
    bg: 'rgba(34, 197, 94, 0.15)',
    label: 'Action',
  },
  risk: {
    icon: FiAlertTriangle,
    color: 'orange.400',
    bg: 'rgba(251, 146, 60, 0.15)',
    label: 'Risque',
  },
  structure: {
    icon: FiLayers,
    color: 'blue.400',
    bg: 'rgba(96, 165, 250, 0.15)',
    label: 'Contexte',
  },
  default: {
    icon: FiCompass,
    color: 'gray.400',
    bg: 'rgba(156, 163, 175, 0.15)',
    label: 'Explore',
  },
}

interface ResearchAxesSectionProps {
  axes: ResearchAxis[]
  onSearch?: (query: string) => void
}

export default function ResearchAxesSection({
  axes,
  onSearch,
}: ResearchAxesSectionProps) {
  const { isOpen, onToggle } = useDisclosure({ defaultIsOpen: false })

  if (!axes || axes.length === 0) {
    return null
  }

  const handleAxisClick = (axis: ResearchAxis) => {
    if (onSearch) {
      onSearch(axis.full_question)
    }
  }

  return (
    <Box
      bg="bg.secondary"
      borderRadius="lg"
      border="1px solid"
      borderColor="border.default"
      overflow="hidden"
    >
      {/* Header */}
      <HStack
        px={3}
        py={2}
        bg="bg.tertiary"
        borderBottom={isOpen ? '1px solid' : 'none'}
        borderColor="border.default"
        cursor="pointer"
        onClick={onToggle}
        _hover={{ bg: 'bg.hover' }}
        justify="space-between"
        transition="all 0.2s"
      >
        <HStack spacing={2}>
          <Icon as={FiCompass} boxSize={4} color="brand.400" />
          <Text fontSize="xs" fontWeight="medium" color="text.primary">
            Pour aller plus loin
          </Text>
          <HStack
            px={1.5}
            py={0.5}
            bg="rgba(99, 102, 241, 0.15)"
            rounded="full"
          >
            <Text fontSize="2xs" fontWeight="medium" color="brand.400">
              {axes.length}
            </Text>
          </HStack>
        </HStack>
        <Icon
          as={isOpen ? ChevronUpIcon : ChevronDownIcon}
          color="text.muted"
          boxSize={4}
        />
      </HStack>

      {/* Content - vertical layout for better readability */}
      <Collapse in={isOpen}>
        <VStack spacing={2} p={3} align="stretch">
          {axes.slice(0, 6).map((axis) => (
            <ResearchAxisCard
              key={axis.axis_id}
              axis={axis}
              onClick={() => handleAxisClick(axis)}
            />
          ))}
        </VStack>
      </Collapse>
    </Box>
  )
}

interface ResearchAxisCardProps {
  axis: ResearchAxis
  onClick: () => void
}

/**
 * Card for a research axis - displays as a clickable question
 * No RDF triplets, just clean readable questions
 */
function ResearchAxisCard({ axis, onClick }: ResearchAxisCardProps) {
  const config = ROLE_CONFIG[axis.role] || ROLE_CONFIG.default

  return (
    <Box
      p={2.5}
      bg={config.bg}
      rounded="lg"
      cursor="pointer"
      _hover={{
        transform: 'translateY(-1px)',
        boxShadow: `0 4px 12px ${config.bg}`,
        bg: axis.role === 'actionnable' ? 'rgba(34, 197, 94, 0.25)' :
            axis.role === 'risk' ? 'rgba(251, 146, 60, 0.25)' :
            'rgba(96, 165, 250, 0.25)',
      }}
      onClick={onClick}
      transition="all 0.2s"
    >
      <HStack spacing={3} align="center">
        {/* Role icon */}
        <Box
          p={1.5}
          bg="bg.tertiary"
          rounded="md"
          flexShrink={0}
        >
          <Icon as={config.icon} boxSize={3.5} color={config.color} />
        </Box>

        {/* Question - clean and readable */}
        <Text
          fontSize="sm"
          fontWeight="medium"
          color="text.primary"
          flex={1}
          noOfLines={2}
        >
          {axis.short_label}
        </Text>

        {/* Role badge + confidence */}
        <HStack spacing={2} flexShrink={0}>
          <Badge
            fontSize="2xs"
            colorScheme={
              axis.role === 'actionnable' ? 'green' :
              axis.role === 'risk' ? 'orange' : 'blue'
            }
            variant="subtle"
          >
            {config.label}
          </Badge>
          <Tooltip
            label={`Confiance: ${Math.round(axis.confidence * 100)}% - Cliquez pour explorer`}
            placement="top"
            fontSize="xs"
          >
            <Box
              w={2}
              h={2}
              rounded="full"
              bg={
                axis.confidence >= 0.7 ? 'green.400' :
                axis.confidence >= 0.4 ? 'yellow.400' : 'gray.400'
              }
            />
          </Tooltip>
        </HStack>
      </HStack>
    </Box>
  )
}
