'use client'

/**
 * OSMOS Research Axes Section - Dark Elegance Edition
 *
 * Displays structured research axes generated by the ResearchAxesEngine.
 */

import {
  Box,
  HStack,
  Text,
  Tooltip,
  Icon,
  Collapse,
  useDisclosure,
  Wrap,
  WrapItem,
} from '@chakra-ui/react'
import {
  ChevronDownIcon,
  ChevronUpIcon,
} from '@chakra-ui/icons'
import { ResearchAxis } from '@/types/api'
import { FiCompass } from 'react-icons/fi'

// Colors for each axis type
const AXIS_CONFIG: Record<string, { color: string; bg: string }> = {
  bridge: { color: 'purple.400', bg: 'rgba(192, 132, 252, 0.15)' },
  weak_signal: { color: 'orange.400', bg: 'rgba(251, 146, 60, 0.15)' },
  cluster: { color: 'teal.400', bg: 'rgba(45, 212, 191, 0.15)' },
  continuity: { color: 'blue.400', bg: 'rgba(96, 165, 250, 0.15)' },
  unexplored: { color: 'green.400', bg: 'rgba(34, 197, 94, 0.15)' },
  transitive: { color: 'cyan.400', bg: 'rgba(34, 211, 238, 0.15)' },
  default: { color: 'gray.400', bg: 'rgba(156, 163, 175, 0.15)' },
}

interface ResearchAxesSectionProps {
  axes: ResearchAxis[]
  onSearch?: (query: string) => void
}

export default function ResearchAxesSection({
  axes,
  onSearch,
}: ResearchAxesSectionProps) {
  const { isOpen, onToggle } = useDisclosure({ defaultIsOpen: false })

  if (!axes || axes.length === 0) {
    return null
  }

  const handleAxisClick = (axis: ResearchAxis) => {
    if (onSearch) {
      onSearch(axis.contextual_question)
    }
  }

  return (
    <Box
      bg="bg.secondary"
      borderRadius="lg"
      border="1px solid"
      borderColor="border.default"
      overflow="hidden"
    >
      {/* Header */}
      <HStack
        px={3}
        py={2}
        bg="bg.tertiary"
        borderBottom={isOpen ? '1px solid' : 'none'}
        borderColor="border.default"
        cursor="pointer"
        onClick={onToggle}
        _hover={{ bg: 'bg.hover' }}
        justify="space-between"
        transition="all 0.2s"
      >
        <HStack spacing={2}>
          <Icon as={FiCompass} boxSize={4} color="brand.400" />
          <Text fontSize="xs" fontWeight="medium" color="text.primary">
            Pistes de recherche
          </Text>
          <HStack
            px={1.5}
            py={0.5}
            bg="rgba(99, 102, 241, 0.15)"
            rounded="full"
          >
            <Text fontSize="2xs" fontWeight="medium" color="brand.400">
              {axes.length}
            </Text>
          </HStack>
        </HStack>
        <Icon
          as={isOpen ? ChevronUpIcon : ChevronDownIcon}
          color="text.muted"
          boxSize={4}
        />
      </HStack>

      {/* Content - horizontal wrap layout */}
      <Collapse in={isOpen}>
        <Wrap spacing={2} p={3}>
          {axes.slice(0, 6).map((axis) => (
            <WrapItem key={axis.axis_id}>
              <ResearchAxisChip
                axis={axis}
                onClick={() => handleAxisClick(axis)}
              />
            </WrapItem>
          ))}
        </Wrap>
      </Collapse>
    </Box>
  )
}

interface ResearchAxisChipProps {
  axis: ResearchAxis
  onClick: () => void
}

/**
 * Compact chip for a research axis
 */
function ResearchAxisChip({ axis, onClick }: ResearchAxisChipProps) {
  const config = AXIS_CONFIG[axis.axis_type] || AXIS_CONFIG.default

  return (
    <Tooltip
      label={axis.contextual_question}
      placement="top"
      hasArrow
      fontSize="xs"
      bg="bg.tertiary"
      color="text.primary"
    >
      <HStack
        px={2.5}
        py={1}
        bg={config.bg}
        rounded="full"
        cursor="pointer"
        _hover={{
          transform: 'translateY(-1px)',
          boxShadow: `0 2px 8px ${config.bg}`,
        }}
        onClick={onClick}
        maxW="200px"
        transition="all 0.2s"
      >
        <Text
          fontSize="xs"
          fontWeight="medium"
          color={config.color}
          noOfLines={1}
        >
          {truncateQuestion(axis.title, 25)}
        </Text>
      </HStack>
    </Tooltip>
  )
}

/**
 * Truncates a question for display
 */
function truncateQuestion(question: string, maxLength: number): string {
  if (question.length <= maxLength) {
    return question
  }
  const truncated = question.substring(0, maxLength)
  const lastSpace = truncated.lastIndexOf(' ')
  if (lastSpace > maxLength * 0.5) {
    return truncated.substring(0, lastSpace) + '...'
  }
  return truncated + '...'
}
