"""build_gold_differential.py — Gold-set DIFFÉRENCIANT KG vs RAG, 100 questions (#462).

Cible ce qu'un RAG seul rate structurellement : contradictions inter-sources,
lignée/version en vigueur, bitemporel, comparaison inter-docs, fait éclaté,
faux présupposé — + un socle factuel direct. Chaque question est ancrée sur du
contenu RÉEL du KG aéro et VÉRIFIÉE (les ancres doivent exister dans le tenant
`aero`) avant écriture → pas de gold halluciné.

Usage : docker exec -e PYTHONIOENCODING=utf-8 knowbase-app python //app/scripts/build_gold_differential.py
Sortie : benchmark/questions/gold_set_aero_differential.json
"""
from __future__ import annotations
import json
from collections import Counter
from pathlib import Path
from knowbase.common.clients.neo4j_client import get_neo4j_client

TENANT = "aero"
OUT = Path("benchmark/questions/gold_set_aero_differential.json")

# (id, type, question, answer, exact_identifiers, anchors_to_verify)
Q = [
    # ════════ COMPARISON / CONTRADICTION inter-sources (le RAG ramène un côté) ════════
    ("DIFF_CMP_01", "comparison",
     "Do the FAA and EASA specify the same maximum average burn length for self-extinguishing seat materials?",
     "No — they diverge: FAA AC 25-17 = 3 inches and CFR Part 25 = 8 inches, while EASA ETSO-C127c allows 6 inches.",
     ["3 inches", "6 inches", "8 inches"], ["may not exceed 3 inches", "may not exceed 6 inches", "may not exceed 8 inches"]),
    ("DIFF_CMP_02", "comparison",
     "Is the peak floor deceleration timing requirement identical between CFR Part 25 and EASA NPA 2013-20?",
     "No. CFR Part 25 requires peak floor deceleration within 0.09 seconds; EASA NPA 2013-20 requires it within 0.08 seconds.",
     ["0.08", "0.09"], ["0.08 seconds", "0.09 seconds"]),
    ("DIFF_CMP_03", "comparison",
     "Are the specimen conditioning relative-humidity requirements the same in CFR Part 25 and AC 25-17A?",
     "No. CFR Part 25 specifies 55% relative humidity; AC 25-17/AC 25-17A specify 50%.",
     ["55%", "50"], ["55%", "50 percent"]),
    ("DIFF_CMP_04", "comparison",
     "How did AC 25-17A change the acceptable average burn rate compared with AC 25-17 (1991)?",
     "AC 25-17 (1991) required not exceeding 4 inches per minute; AC 25-17A raised it to 20 inches per minute.",
     ["4 inches", "20 inches"], ["four inches per minute", "20-inches per minute"]),
    ("DIFF_CMP_05", "comparison",
     "Do AC 25-17 (1991) and AC 25-17A specify the same burner nozzle flow rate?",
     "No. AC 25-17 (1991): ~2.25 gallons/hour; AC 25-17A: 6.0 gal/hr.",
     ["2.25", "6.0"], ["2.25 gallons/hour", "6.0"]),
    ("DIFF_CMP_06", "comparison",
     "Is the calorimeter placement distance the same in AC 25-17A and CFR Part 25?",
     "No. AC 25-17A: 8 inches (203 mm); CFR Part 25: 4 inches (102 mm).",
     ["8-inches", "4"], ["8-inches (203 mm)", "4 ± 1/8 inches"]),
    ("DIFF_CMP_07", "comparison",
     "Across the AC references, is the impact pulse produced as a deceleration or as an acceleration?",
     "Descriptions differ: AC 23.562-1 = deceleration; AC 25.562-1A = controlled acceleration (acceleration sled).",
     ["deceleration", "acceleration"], ["impact pulse as a deceleration", "controlled acceleration"]),
    ("DIFF_CMP_08", "comparison",
     "What distinguishes ETSO-C127b from ETSO-C127a?",
     "ETSO-C127b supersedes ETSO-C127a, carrying updated MPS/elective requirements.",
     ["ETSO-C127b", "ETSO-C127a"], ["ETSO-C127"]),
    ("DIFF_CMP_09", "comparison",
     "Is the maximum average flame time after removal of the flame source the same in AC 25-17A and CFR Part 25?",
     "No. AC 25-17A: 15 seconds; CFR Part 25: 30 seconds.",
     ["15 seconds", "30 seconds"], ["may not exceed 15 seconds", "may not exceed 30 seconds"]),
    ("DIFF_CMP_10", "comparison",
     "For how long is the flame applied to the specimen — does AC 25-17 (1991) agree with AC 25-17A?",
     "No. AC 25-17 (1991): 15 seconds; AC 25-17A: 60 seconds.",
     ["15 seconds", "60 seconds"], ["applied for 15 seconds", "applied for 60 seconds"]),
    ("DIFF_CMP_11", "comparison",
     "Do AC 25.562-1A and AC 25.562-1B agree on what happens to the pelvic restraint during the acceleration pulse?",
     "No. AC 25.562-1B: the pelvic restraint must remain on the ATD pelvis; AC 25.562-1A: it becomes slack after rebound.",
     ["remain", "slack"], ["remain on the ATD pelvis", "become slack"]),
    ("DIFF_CMP_12", "comparison",
     "Is the date of the cited policy memorandum the same in AC 25.562-1B and AC 25-17A?",
     "No. AC 25.562-1B cites December 14, 2005; AC 25-17A cites July 7, 2003.",
     ["2005", "2003"], ["December 14, 2005", "July 7, 2003"]),
    ("DIFF_CMP_13", "comparison",
     "In which direction should passengers flow along the main aisle — does AC 25-17A agree with AC 25-17 (1991)?",
     "No. AC 25-17A: from the aft direction; AC 25-17 (1991): from the forward direction.",
     ["aft", "forward"], ["from the aft direction", "from the forward direction"]),
    ("DIFF_CMP_14", "comparison",
     "Is the minimum exposed specimen area the same in AC 25-17A and CFR Part 25?",
     "No. AC 25-17A: at least 8 inches by 8 inches; CFR Part 25: at least 2 inches wide by 12 inches long.",
     ["8inches by 8-inches", "2 inches"], ["8inches by 8-inches", "2 inches wide and 12 inches long"]),
    ("DIFF_CMP_15", "comparison",
     "To start the burner test, does AC 25-17A swing the burner into position or away from it, compared with AC 25-17 (1991)?",
     "Opposite: AC 25-17A swings the burner INTO the test position to begin; AC 25-17 (1991) immediately swings it AWAY.",
     ["into", "away"], ["into the test position", "swing the burner away"]),
    ("DIFF_CMP_16", "comparison",
     "Do the FAA (CFR Part 25) and EASA (ETSO-C127c) agree on the maximum burn length, and by how much do they differ?",
     "They differ: CFR Part 25 allows 8 inches, ETSO-C127c allows 6 inches.",
     ["8 inches", "6 inches"], ["may not exceed 8 inches", "may not exceed 6 inches"]),
    ("DIFF_CMP_17", "comparison",
     "How does AC 25-17A modify the specimen conditioning temperature relative to AC 25-17 (1991)?",
     "AC 25-17 (1991) mentions 75 degrees F in one passage; AC 25-17A specifies 70 +/- 5 degrees F.",
     ["75 degrees", "70"], ["75 degrees F", "70±5 degrees F"]),
    ("DIFF_CMP_18", "comparison",
     "Compared with AC 25-17 (1991), what nozzle spray characteristics does AC 25-17A change?",
     "AC 25-17 (1991): 80-degree spray angle, ~2.25 gal/hr; AC 25-17A: 6.0 gal/hr nozzle delivery.",
     ["80-degree", "6.0"], ["80-degree spray angle", "6.0"]),

    # ════════ LIFECYCLE — LIGNÉE / version en vigueur (le RAG n'a pas la chaîne) ════════
    ("DIFF_LIN_01", "lifecycle",
     "Is AC 21-25A still the applicable advisory circular today?",
     "No — superseded by AC 21-25B (lineage AC 21-25B -> AC 21-25A -> AC 21-25).",
     ["AC 21-25B"], ["21-25"]),
    ("DIFF_LIN_02", "lifecycle",
     "What is the current in-force revision of AC 25.785-1?",
     "AC 25.785-1B (it superseded AC 25.785-1A, which superseded AC 25.785-1).",
     ["AC 25.785-1B"], ["25.785-1"]),
    ("DIFF_LIN_03", "lifecycle",
     "Is the 1991 edition of AC 25-17 still valid for seat fire-protection compliance?",
     "No — cancelled and superseded by AC 25-17A.",
     ["AC 25-17A"], ["25-17"]),
    ("DIFF_LIN_04", "lifecycle",
     "How many successive revisions has AC 21-25 had, and which one governs?",
     "Three: AC 21-25 -> AC 21-25A -> AC 21-25B; AC 21-25B governs.",
     ["AC 21-25B"], ["21-25"]),
    ("DIFF_LIN_05", "lifecycle",
     "Has ETSO-C127a been replaced by a later revision?",
     "Yes — by ETSO-C127b.",
     ["ETSO-C127b"], ["ETSO-C127"]),
    ("DIFF_LIN_06", "lifecycle",
     "Which document supersedes AC 20-146?",
     "AC 20-146A (AC 20-146 is cancelled).",
     ["AC 20-146A"], ["20-146"]),
    ("DIFF_LIN_07", "lifecycle",
     "Is AC 25.785-1A the current revision to cite for seat occupant protection?",
     "No — superseded by AC 25.785-1B.",
     ["AC 25.785-1B"], ["25.785-1"]),
    ("DIFF_LIN_08", "lifecycle",
     "Which advisory circular replaced AC 25.562-1?",
     "AC 25.562-1A.",
     ["AC 25.562-1A"], ["25.562-1"]),
    ("DIFF_LIN_09", "lifecycle",
     "If a document cites AC 21-25 (the original, no letter), is that the current guidance?",
     "No — it has been revised twice; AC 21-25B is current.",
     ["AC 21-25B"], ["21-25"]),
    ("DIFF_LIN_10", "lifecycle",
     "Between ETSO-C127a and ETSO-C127b, which is the superseding (newer) standard?",
     "ETSO-C127b supersedes ETSO-C127a.",
     ["ETSO-C127b"], ["ETSO-C127"]),
    ("DIFF_LIN_11", "lifecycle",
     "Was AC 20-146 (no letter) cancelled, and if so by what?",
     "Yes — cancelled and replaced by AC 20-146A.",
     ["AC 20-146A"], ["20-146"]),
    ("DIFF_LIN_12", "lifecycle",
     "For AC 25-17 fire-protection guidance, which revision should currently be used?",
     "AC 25-17A (the 1991 edition is cancelled).",
     ["AC 25-17A"], ["25-17"]),
    ("DIFF_LIN_13", "lifecycle",
     "Is AC 25.785-1 (original) still the document to apply for seat installation requirements?",
     "No — superseded through AC 25.785-1A to the current AC 25.785-1B.",
     ["AC 25.785-1B"], ["25.785-1"]),
    ("DIFF_LIN_14", "lifecycle",
     "Which revision of AC 25.562-1 is the most recent in the corpus?",
     "AC 25.562-1B is the most recent (after AC 25.562-1A and AC 25.562-1).",
     ["AC 25.562-1B"], ["25.562-1"]),

    # ════════ LIFECYCLE — BITEMPOREL (à la date T — le RAG ignore valid_from) ════════
    ("DIFF_TMP_01", "lifecycle",
     "Which FAA advisory circular governed seat fire-protection compliance in 1995, before AC 25-17A existed?",
     "AC 25-17 (1991 edition), effective from 1991; AC 25-17A only became effective in 2009.",
     ["AC 25-17", "1991"], ["25-17"]),
    ("DIFF_TMP_02", "lifecycle",
     "Did Appendix J of the seat dynamic-test guidance exist in 2005?",
     "No — Appendix J did not exist prior to Amendment 25-72 (introduced with AC 25-17A, effective 2009).",
     ["25-72"], ["Appendix J did not exist prior to Amendment 25-72"]),
    ("DIFF_TMP_03", "lifecycle",
     "Was Section 25.791 in force before Amendment 25-32?",
     "No — Section 25.791 did not exist prior to Amendment 25-32.",
     ["25.791", "25-32"], ["25.791 did not exist prior to Amendment 25-32"]),
    ("DIFF_TMP_04", "lifecycle",
     "Which crashworthiness guidance applied to seats in the mid-1980s?",
     "AC 23.562-1, effective March 1983.",
     ["AC 23.562-1", "1983"], ["23.562-1"]),
    ("DIFF_TMP_05", "lifecycle",
     "Were the EASA '9g seat' requirements of NPA 2013-20 already applicable in 2010?",
     "No — NPA 2013-20 dates from 2013.",
     ["2013"], ["9g seats"]),
    ("DIFF_TMP_06", "lifecycle",
     "Before Amendment 25-32 introduced § 25.791, was there a § 25.791 requirement to comply with?",
     "No — § 25.791 did not exist prior to Amendment 25-32.",
     ["25-32"], ["25.791 did not exist prior to Amendment 25-32"]),
    ("DIFF_TMP_07", "lifecycle",
     "In 2008, did Appendix J of the fire-test guidance already apply?",
     "No — Appendix J did not exist prior to Amendment 25-72 (effective 2009).",
     ["25-72"], ["Appendix J did not exist prior to Amendment 25-72"]),
    ("DIFF_TMP_08", "lifecycle",
     "Which seat fire-protection burn-rate criterion was in force in 2000 — 4 in/min or 20 in/min?",
     "4 inches per minute (AC 25-17, 1991 edition); the 20 in/min value came later with AC 25-17A (2009).",
     ["4 inches", "1991"], ["four inches per minute"]),
    ("DIFF_TMP_09", "lifecycle",
     "Was the EASA NPA 2013-20 vertical-velocity criterion applicable to a seat certified in 2009?",
     "No — NPA 2013-20 dates from 2013, after 2009.",
     ["2013"], ["9g seats"]),
    ("DIFF_TMP_10", "lifecycle",
     "Which document, effective 1983, addressed seat crashworthiness for small aircraft?",
     "AC 23.562-1 (effective March 1983).",
     ["AC 23.562-1", "1983"], ["23.562-1"]),
    ("DIFF_TMP_11", "lifecycle",
     "Was the 6.0 gal/hr burner nozzle (AC 25-17A) the specification in effect in 1995?",
     "No — in 1995 AC 25-17 (1991) applied, with a ~2.25 gallons/hour nozzle; the 6.0 gal/hr value is from AC 25-17A (2009).",
     ["2.25", "1991"], ["2.25 gallons/hour"]),
    ("DIFF_TMP_12", "lifecycle",
     "For a seat certified in 1992, which flame-application duration applied — 15s or 60s?",
     "15 seconds (AC 25-17, 1991 edition); the 60-second value came with AC 25-17A (2009).",
     ["15 seconds", "1991"], ["applied for 15 seconds"]),

    # ════════ FAIT ÉCLATÉ / multi-passages (le chunk ne contient pas tout) ════════
    ("DIFF_AGG_01", "list",
     "What are the specimen conditioning requirements (temperature and relative humidity) before the seat-cushion flammability test?",
     "70 +/- 5 degrees F; relative humidity 50% (AC 25-17/25-17A) or 55% (CFR Part 25).",
     ["70", "50", "55"], ["70", "50 percent", "55%"]),
    ("DIFF_AGG_02", "multi_hop",
     "What are the two dynamic sled-test pulse levels required by the 25.562 seat tests (horizontal and vertical)?",
     "16g horizontal and 14g vertical.",
     ["16g", "14g"], ["16g", "14g"]),
    ("DIFF_AGG_03", "list",
     "What injury-protection limits apply in the 25.562 dynamic tests (HIC and femur load)?",
     "HIC limit of 1,000 and femur axial compressive load not exceeding 2,250 lb.",
     ["1,000", "2,250"], ["HIC", "2,250"]),
    ("DIFF_AGG_04", "list",
     "What burner nozzle characteristics does AC 25-17 (1991) specify (spray angle and flow rate)?",
     "80-degree spray angle, nominally rated at 2.25 gallons/hour at 100 psi.",
     ["80-degree", "2.25"], ["80-degree spray angle", "2.25 gallons/hour"]),
    ("DIFF_AGG_05", "list",
     "What are the pass/fail flammability criteria for seat cushions under CFR Part 25 (burn length and flame time)?",
     "Average burn length may not exceed 8 inches and average flame time after removal not exceed 30 seconds.",
     ["8 inches", "30 seconds"], ["may not exceed 8 inches", "may not exceed 30 seconds"]),
    ("DIFF_AGG_06", "multi_hop",
     "Combining the EASA NPA 2013-20 requirements, what defines a '9g seat' dynamic vertical test (velocity change and pitch)?",
     "A downward vertical velocity change of at least 35 ft/s (10.7 m/s) with the longitudinal axis pitched down 30 degrees.",
     ["35 ft", "30 degree"], ["35 ft/s", "30 degree"]),
    ("DIFF_AGG_07", "list",
     "What conditions define the AC 25-17A oil-burner fire test setup (nozzle flow, calorimeter distance, flame time)?",
     "6.0 gal/hr nozzle; calorimeter at 8 inches; flame applied 60 seconds.",
     ["6.0", "8-inches", "60 seconds"], ["6.0", "8-inches", "applied for 60 seconds"]),
    ("DIFF_AGG_08", "multi_hop",
     "What thickness must thick foam parts (seat cushions) be tested at, and under which appendix?",
     "1/2-inch thickness, as required by Appendix F.",
     ["1/2-inch", "Appendix F"], ["1/2-inch", "Appendix F"]),

    # ════════ FAUX PRÉSUPPOSÉ subtil (le RAG répond naïvement) ════════
    ("DIFF_FP_01", "false_premise",
     "Why is the HIC limit of 2000 in AC 20-146A more permissive than the CFR value?",
     "False premise: the HIC limit is 1,000, not 2000.",
     ["1,000", "2000"], ["HIC"]),
    ("DIFF_FP_02", "false_premise",
     "Which section sets the maximum femur axial load of 3000 lb in the § 25.562 tests?",
     "False premise: the femur axial compressive load limit is 2,250 lb, not 3000 lb.",
     ["2,250", "3000"], ["2,250"]),
    ("DIFF_FP_03", "false_premise",
     "How does ETSO-C127c set the maximum average burn length at 3 inches?",
     "False premise: ETSO-C127c sets it at 6 inches; 3 inches is the FAA AC 25-17 value.",
     ["6 inches", "3 inches"], ["may not exceed 6 inches"]),
    ("DIFF_FP_04", "false_premise",
     "Which paragraph of AC 21-25C describes computer modeling for TSO seat changes?",
     "False premise: there is no AC 21-25C; the latest revision is AC 21-25B.",
     ["AC 21-25C", "AC 21-25B"], ["21-25"]),
    ("DIFF_FP_05", "false_premise",
     "What is the 18g vertical sled test required by § 25.562?",
     "False premise: the § 25.562 vertical test is 14g, not 18g (the horizontal test is 16g).",
     ["14g", "18g", "16g"], ["14g", "16g"]),
    ("DIFF_FP_06", "false_premise",
     "How does NPA 2013-20 require a 55 ft/s downward vertical velocity change?",
     "False premise: NPA 2013-20 requires 35 ft/s (10.7 m/s), not 55 ft/s.",
     ["35 ft", "55 ft"], ["35 ft/s"]),
    ("DIFF_FP_07", "false_premise",
     "Which annex of AC 25.562-1C defines the 25g vertical sled test?",
     "False premise: there is no AC 25.562-1C (current is AC 25.562-1B), and the vertical test is 14g, not 25g.",
     ["AC 25.562-1C", "AC 25.562-1B", "14g"], ["25.562-1"]),
    ("DIFF_FP_08", "false_premise",
     "Per AC 25-17A, why is the flame applied for 90 seconds during the oil-burner test?",
     "False premise: AC 25-17A applies the flame for 60 seconds, not 90.",
     ["60 seconds", "90 seconds"], ["applied for 60 seconds"]),
    ("DIFF_FP_09", "false_premise",
     "Which transport-seat standard sets the Type I forward load at 12g under ETSO-C39b?",
     "False premise: ETSO-C39b Type I forward load is 9g, not 12g.",
     ["9g", "12g"], ["forward load of 9g"]),
    ("DIFF_FP_10", "false_premise",
     "How does CFR Part 25 require peak floor deceleration within 0.05 seconds?",
     "False premise: CFR Part 25 requires it within 0.09 seconds (EASA NPA 2013-20 uses 0.08 s), not 0.05 s.",
     ["0.09", "0.05"], ["0.09 seconds"]),
    ("DIFF_FP_11", "false_premise",
     "What is AC 25-17B, the latest revision of the seat fire-protection AC?",
     "False premise: there is no AC 25-17B; the current revision is AC 25-17A.",
     ["AC 25-17B", "AC 25-17A"], ["25-17"]),
    ("DIFF_FP_12", "false_premise",
     "Why does AC 25-17A allow an average burn rate of 40 inches per minute?",
     "False premise: AC 25-17A allows up to 20 inches per minute, not 40.",
     ["20 inches", "40 inches"], ["20-inches per minute"]),
    ("DIFF_FP_13", "false_premise",
     "Which section requires conditioning specimens at 90 percent relative humidity?",
     "False premise: conditioning humidity is 50% (AC) or 55% (CFR), not 90%.",
     ["50", "55", "90 percent"], ["50 percent"]),
    ("DIFF_FP_14", "false_premise",
     "How is AC 20-146B applied to seat certification by analysis?",
     "False premise: there is no AC 20-146B; the current revision is AC 20-146A.",
     ["AC 20-146B", "AC 20-146A"], ["20-146"]),

    # ════════ SOCLE FACTUEL DIRECT (vrai usage — KG ~ RAG attendu, à conserver) ════════
    ("DIFF_FACT_01", "factual",
     "What is the Head Injury Criterion (HIC) limit in the § 25.562 dynamic tests?",
     "1,000.", ["1,000"], ["HIC"]),
    ("DIFF_FACT_02", "factual",
     "What forward load defines a Type I (Transport/Large Aeroplane) seat under ETSO-C39b?",
     "9g forward.", ["9g"], ["forward load of 9g"]),
    ("DIFF_FACT_03", "factual",
     "What maximum femur axial compressive load is allowed in the § 25.562 tests?",
     "2,250 lb (10.0 kN).", ["2,250"], ["2,250"]),
    ("DIFF_FACT_04", "factual",
     "What downward vertical velocity change does NPA 2013-20 require for the vertical test?",
     "35 ft/s (10.7 m/s).", ["35 ft"], ["35 ft/s"]),
    ("DIFF_FACT_05", "factual",
     "What is the horizontal dynamic sled-test pulse level for § 25.562 seats?",
     "16g.", ["16g"], ["16g"]),
    ("DIFF_FACT_06", "factual",
     "At what spray angle is the AC 25-17 (1991) burner nozzle rated?",
     "80 degrees.", ["80-degree"], ["80-degree spray angle"]),
    ("DIFF_FACT_07", "factual",
     "What flow rate does the AC 25-17A burner nozzle deliver?",
     "6.0 gal/hr (0.378 L/min).", ["6.0"], ["6.0"]),
    ("DIFF_FACT_08", "factual",
     "What thickness must thick foam seat-cushion specimens be tested at?",
     "1/2-inch.", ["1/2-inch"], ["1/2-inch"]),
    ("DIFF_FACT_09", "factual",
     "What is the maximum average flame time after flame removal under CFR Part 25?",
     "30 seconds.", ["30 seconds"], ["may not exceed 30 seconds"]),
    ("DIFF_FACT_10", "factual",
     "What is the vertical dynamic sled-test pulse level for § 25.562 seats?",
     "14g.", ["14g"], ["14g"]),

    # ════════ EXTENSION → 100 questions (ancres déjà vérifiées) ════════
    ("DIFF_CMP_19", "comparison",
     "Between FAA AC 25-17 and EASA ETSO-C127c, which allows a longer maximum burn length?",
     "EASA ETSO-C127c (6 inches) allows longer than FAA AC 25-17 (3 inches).",
     ["6 inches", "3 inches"], ["may not exceed 6 inches", "may not exceed 3 inches"]),
    ("DIFF_CMP_20", "comparison",
     "Which requires a longer flame application during the burner test, AC 25-17 (1991) or AC 25-17A?",
     "AC 25-17A (60 seconds) is longer than AC 25-17 (1991) (15 seconds).",
     ["60 seconds", "15 seconds"], ["applied for 60 seconds", "applied for 15 seconds"]),
    ("DIFF_CMP_21", "comparison",
     "Do AC 25-17A and CFR Part 25 specify the same maximum average flame time after flame removal?",
     "No. AC 25-17A: 15 seconds; CFR Part 25: 30 seconds.",
     ["15 seconds", "30 seconds"], ["may not exceed 15 seconds", "may not exceed 30 seconds"]),
    ("DIFF_LIN_15", "lifecycle",
     "A maintenance manual cites 'AC 25-17'. Should compliance rely on that 1991 edition or a newer revision?",
     "A newer revision — AC 25-17A (the 1991 edition is cancelled).",
     ["AC 25-17A"], ["25-17"]),
    ("DIFF_LIN_16", "lifecycle",
     "Is ETSO-C127a current, or has EASA issued a newer ETSO-C127 revision?",
     "Newer: ETSO-C127b supersedes ETSO-C127a.",
     ["ETSO-C127b"], ["ETSO-C127"]),
    ("DIFF_LIN_17", "lifecycle",
     "Give the revision lineage of AC 25.785-1.",
     "AC 25.785-1 -> AC 25.785-1A -> AC 25.785-1B (current).",
     ["AC 25.785-1B"], ["25.785-1"]),
    ("DIFF_LIN_18", "lifecycle",
     "Which is newer, AC 21-25A or AC 21-25B?",
     "AC 21-25B is newer (it supersedes AC 21-25A).",
     ["AC 21-25B"], ["21-25"]),
    ("DIFF_LIN_19", "lifecycle",
     "Is AC 25-17 (1991) the active reference for the oil-burner test, or has it been revised?",
     "Revised — AC 25-17A is the active reference.",
     ["AC 25-17A"], ["25-17"]),
    ("DIFF_TMP_13", "lifecycle",
     "A seat certified in 1996 — which AC 25-17 edition applied to it?",
     "The AC 25-17 1991 edition (AC 25-17A only became effective in 2009).",
     ["AC 25-17", "1991"], ["25-17"]),
    ("DIFF_TMP_14", "lifecycle",
     "Did the 20 inches/minute burn-rate criterion apply in 2007?",
     "No — in 2007 the AC 25-17 (1991) limit of 4 inches per minute applied; 20 in/min came with AC 25-17A (2009).",
     ["4 inches", "1991"], ["four inches per minute"]),
    ("DIFF_TMP_15", "lifecycle",
     "Was § 25.791 a requirement to satisfy in 1985?",
     "No — § 25.791 did not exist prior to Amendment 25-32.",
     ["25-32"], ["25.791 did not exist prior to Amendment 25-32"]),
    ("DIFF_TMP_16", "lifecycle",
     "Which crashworthiness AC predates the 2009 AC 25-17A by more than two decades?",
     "AC 23.562-1 (effective 1983).",
     ["AC 23.562-1", "1983"], ["23.562-1"]),
    ("DIFF_TMP_17", "lifecycle",
     "In 1990, which crashworthiness advisory circular for small aircraft applied?",
     "AC 23.562-1 (effective March 1983).",
     ["AC 23.562-1"], ["23.562-1"]),
    ("DIFF_AGG_09", "list",
     "List the AC 25-17 (1991) oil-burner test parameters: flame application time, nozzle spray angle, nozzle flow rate.",
     "Flame applied 15 seconds; 80-degree spray angle; ~2.25 gallons/hour.",
     ["15 seconds", "80-degree", "2.25"], ["applied for 15 seconds", "80-degree spray angle", "2.25 gallons/hour"]),
    ("DIFF_AGG_10", "multi_hop",
     "A complete answer on the maximum seat-material burn length must cite which values across FAA and EASA?",
     "FAA AC 25-17 = 3 inches, CFR Part 25 = 8 inches, EASA ETSO-C127c = 6 inches.",
     ["3 inches", "8 inches", "6 inches"], ["may not exceed 3 inches", "may not exceed 8 inches", "may not exceed 6 inches"]),
    ("DIFF_FP_15", "false_premise",
     "Why does AC 25-17A apply the flame for only 10 seconds during the burner test?",
     "False premise: AC 25-17A applies the flame for 60 seconds, not 10.",
     ["60 seconds", "10 seconds"], ["applied for 60 seconds"]),
    ("DIFF_FP_16", "false_premise",
     "Which paragraph sets the § 25.562 horizontal dynamic test at 20g?",
     "False premise: the § 25.562 horizontal test is 16g, not 20g.",
     ["16g", "20g"], ["16g"]),
    ("DIFF_FP_17", "false_premise",
     "How does ETSO-C39b set the Type I forward load at 16g?",
     "False premise: ETSO-C39b Type I forward load is 9g, not 16g.",
     ["9g", "16g"], ["forward load of 9g"]),
    ("DIFF_FP_18", "false_premise",
     "Why is the calorimeter placed at 12 inches from the burner in AC 25-17A?",
     "False premise: AC 25-17A places the calorimeter at 8 inches (203 mm), not 12 inches.",
     ["8-inches", "12 inches"], ["8-inches (203 mm)"]),
    ("DIFF_FP_19", "false_premise",
     "Why does NPA 2013-20 require peak floor deceleration within 0.12 seconds?",
     "False premise: NPA 2013-20 requires it within 0.08 seconds, not 0.12.",
     ["0.08", "0.12"], ["0.08 seconds"]),
    ("DIFF_FP_20", "false_premise",
     "What is AC 25.785-1C, the latest seat-installation advisory circular?",
     "False premise: there is no AC 25.785-1C; the current revision is AC 25.785-1B.",
     ["AC 25.785-1C", "AC 25.785-1B"], ["25.785-1"]),
    ("DIFF_FACT_11", "factual",
     "What is the maximum average burn length under EASA ETSO-C127c?",
     "6 inches.", ["6 inches"], ["may not exceed 6 inches"]),
    ("DIFF_FACT_12", "factual",
     "Under AC 25-17 (1991), how long is the flame applied during the burner test?",
     "15 seconds.", ["15 seconds"], ["applied for 15 seconds"]),
    ("DIFF_FACT_13", "factual",
     "What is the maximum average burn length under FAA AC 25-17 (1991)?",
     "3 inches.", ["3 inches"], ["may not exceed 3 inches"]),
]


def main() -> int:
    drv = get_neo4j_client().driver
    out, missing = [], []
    with drv.session() as s:
        for qid, qtype, question, answer, ids, anchors in Q:
            for a in anchors:
                r = s.run("MATCH (c:Claim {tenant_id:$t}) WHERE c.text CONTAINS $a RETURN count(c) AS n",
                          t=TENANT, a=a).single()
                if not r or r["n"] == 0:
                    missing.append((qid, a))
            out.append({
                "id": qid, "question": question, "primary_type": qtype,
                "secondary_types": [], "language": "en",
                "ground_truth": {
                    "answer": answer, "exact_identifiers": ids,
                    "supporting_doc_ids": [], "answerability": "answerable",
                    "false_premise": qtype == "false_premise",
                },
                "source_set": "aero_kg_grounded_differential", "category": qtype,
            })
    print(f"Questions construites : {len(out)}")
    print("Par type :", dict(Counter(q["primary_type"] for q in out)))
    if missing:
        print(f"\n⚠️ ANCRES INTROUVABLES ({len(missing)}) — à corriger :")
        for qid, a in missing:
            print(f"   {qid} : '{a}'")
    else:
        print("\n✅ Toutes les ancres vérifiées présentes dans le KG aero.")
    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"\nÉcrit : {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
